add yamllint to pre-commit hook

diff --git a/.git-hooks/pre-commit b/.git-hooks/pre-commit
--- a/.git-hooks/pre-commit
+++ b/.git-hooks/pre-commit
@@ -21,6 +21,17 @@ for file in $(git diff-index --cached --name-only -z ${against}); do
     fi
   fi
 
+  if command -v yamllint &> /dev/null ; then
+    if [[ "${file}" == "*.yml" ]] || [[ "${file}" == "*.yaml" ]]; then
+      ret_comment=$(yamllint "${file}")
+      ret_code=$?
+      if [[ ${exit_code} -eq 0 ]] && [[ ${ret_code} -ne 0 ]]; then
+        echo "ERROR: ${ret_comment}"
+        exit_code=1
+      fi
+    fi
+  fi
+
   # Run ansible-vault check for vaulted files
   if [[ "${file}" == "vault_*" ]] || [[ "${file}" == "*.vault" ]]; then
     file_status_index=$(git status --porcelain -- "$file" 2>&1 | cut -c1-2)
